### ISSUE TITLE
will it delete images from the docker-registry ?

### ISSUE THREAD

**Issue by MastanaGuru** [dmytrostriletskyi/stale-feature-branch-operator#9]
I am trying to use it with openshift. Will the operator delete imagestreams and routes ?

**Comment by dmytrostriletskyi** [comment]
@MastanaGuru, hi! 

Sorry for my late response. It should delete everything under a namespace.

You can check by adding new resources going through the [tutorial](https://github.com/dmytrostriletskyi/stale-feature-branch-operator#guideline).
